title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.


remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Carlos Pereira Atencio
sticky_navigation: true
prev_next_buttons_location: both
hljs_style: github-gist
